---
deployment:
      tasks:
        - export $DEPLOYPATH=/home/d3donv2ifsil/test  # Add /<app_folder> if required 
        - /bin/cp * -r $DEPLOYPATH                      #copy all from sub folder root
        